apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs"
  labels:
    app: discourse-web
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
        storage: 1Gi