apiVersion: v1
kind: Service
metadata:
  name: discourse-web
  labels:
    app: discourse-web
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: discourse-web
  sessionAffinity: None
  type: ClusterIP